# Form implementation generated from reading ui file 'addPointDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(241, 200)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ressources/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.nameEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.latEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.latEdit.setObjectName("latEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.latEdit)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.longEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.longEdit.setObjectName("longEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.longEdit)
        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.payloadEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.payloadEdit.setObjectName("payloadEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.payloadEdit)
        self.okButton = QtWidgets.QPushButton(parent=Dialog)
        self.okButton.setGeometry(QtCore.QRect(150, 170, 75, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(70, 170, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.usexyCheckBox = QtWidgets.QCheckBox(parent=Dialog)
        self.usexyCheckBox.setGeometry(QtCore.QRect(10, 140, 161, 18))
        self.usexyCheckBox.setObjectName("usexyCheckBox")
        self.line = QtWidgets.QFrame(parent=Dialog)
        self.line.setGeometry(QtCore.QRect(10, 120, 211, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Point"))
        self.label_3.setText(_translate("Dialog", "Point Name:"))
        self.nameEdit.setPlaceholderText(_translate("Dialog", "Wapoint (default)"))
        self.label.setText(_translate("Dialog", "Point latitude: "))
        self.latEdit.setPlaceholderText(_translate("Dialog", "insert latitude..."))
        self.label_2.setText(_translate("Dialog", "Point longitude: "))
        self.longEdit.setPlaceholderText(_translate("Dialog", "insert longitude..."))
        self.label_4.setText(_translate("Dialog", "Payload to drop: "))
        self.payloadEdit.setPlaceholderText(_translate("Dialog", "insert mass..."))
        self.okButton.setText(_translate("Dialog", "Ok"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.usexyCheckBox.setText(_translate("Dialog", "Use x-y instead of lat-long"))
