# Form implementation generated from reading ui file 'addZoneDialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 270)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ressources/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(10, 100, 231, 131))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 229, 129))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 0, 231, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.widget_2 = QtWidgets.QWidget(parent=self.frame)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 231, 30))
        self.widget_2.setStyleSheet("#widget_2 {\n"
"border: 1px solid rgb(182, 184, 195);\n"
"border-radius: 3px;\n"
"background-color: qlineargradient(spread:pad, x1:0.0400505, y1:1, x2:0.672, y2:0.0738636, stop:0 rgba(205, 205, 205, 255), stop:1 rgba(238, 238, 238, 255))\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(5, 5, 131, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_16.setGeometry(QtCore.QRect(187, 5, 20, 21))
        self.pushButton_16.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ressources/gear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_16.setIcon(icon1)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_17.setGeometry(QtCore.QRect(207, 5, 21, 21))
        self.pushButton_17.setObjectName("pushButton_17")
        self.addzoneButton = QtWidgets.QPushButton(parent=self.frame)
        self.addzoneButton.setGeometry(QtCore.QRect(0, 30, 231, 20))
        self.addzoneButton.setObjectName("addzoneButton")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.label_2.setObjectName("label_2")
        self.okButton = QtWidgets.QPushButton(parent=Dialog)
        self.okButton.setGeometry(QtCore.QRect(170, 240, 75, 23))
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(90, 240, 75, 23))
        self.cancelButton.setObjectName("cancelButton")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 231, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 0, 1, 1)
        self.marginEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.marginEdit.setEnabled(False)
        self.marginEdit.setObjectName("marginEdit")
        self.gridLayout.addWidget(self.marginEdit, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create zone"))
        self.label_4.setText(_translate("Dialog", "Waypoint name"))
        self.pushButton_17.setText(_translate("Dialog", "X"))
        self.addzoneButton.setText(_translate("Dialog", "+"))
        self.label_2.setText(_translate("Dialog", "Bounds:"))
        self.okButton.setText(_translate("Dialog", "Ok"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.label_3.setText(_translate("Dialog", "Add noflyzone"))
        self.label.setText(_translate("Dialog", "Name:"))
        self.nameEdit.setPlaceholderText(_translate("Dialog", "Zone (default)"))
        self.checkBox.setText(_translate("Dialog", "Custom margin:"))
        self.marginEdit.setPlaceholderText(_translate("Dialog", "margin..."))
